### ISSUE TITLE
Apt: Errors were encountered while processing:  system76-r8125-dkms

### ISSUE THREAD

**Issue by lisanhu** [pop-os/system76-r8125-dkms#1]
Thank you so much for maintaining this! Recently, I've seen error messages from apt about the package system76-r8125-dkms. Would you please take a look at this issue? Thank you so much!

**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
system76-r8125-dkms:
  Installed: 1.0.0~1554822584~19.10~b461c3e
  Candidate: 1.0.0~1554822584~19.10~b461c3e
  Version table:
 *** 1.0.0~1554822584~19.10~b461c3e 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
After using `sudo apt update && sudo apt upgrade`
I got errors 
```
Errors were encountered while processing:
 system76-r8125-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Steps to reproduce (if you know):**
On my system it's just `sudo apt-get -f install`

**Expected behavior:**
Apt should be run smoothly

**Other Notes:**
The full error messages from apt:
```
[ lisanhu@pop-os : ~ ]
 ~ $ sudo apt-get -f install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up system76-r8125-dkms (1.0.0~1554822584~19.10~b461c3e) ...
Removing old system76-r8125-1.0.0~1554822584~19.10~b461c3e DKMS files...

------------------------------
Deleting module version: 1.0.0~1554822584~19.10~b461c3e
completely from the DKMS tree.
------------------------------
Done.
Loading new system76-r8125-1.0.0~1554822584~19.10~b461c3e DKMS files...
Building for 5.3.0-7625-generic
Building initial module for 5.3.0-7625-generic
ERROR (dkms apport): kernel package linux-headers-5.3.0-7625-generic is not supported
Error! Bad return status for module build on kernel: 5.3.0-7625-generic (x86_64)
Consult /var/lib/dkms/system76-r8125/1.0.0~1554822584~19.10~b461c3e/build/make.log for more information.
dpkg: error processing package system76-r8125-dkms (--configure):
 installed system76-r8125-dkms package post-installation script subprocess returned error exit status 10
Processing triggers for initramfs-tools (0.133ubuntu10pop0) ...
update-initramfs: Generating /boot/initrd.img-5.3.0-7625-generic
kernelstub.Config    : INFO     Looking for configuration...
kernelstub           : INFO     System information: 

    OS:..................Pop!_OS 19.10
    Root partition:....../dev/nvme0n1p3
    Root FS UUID:........11daa085-26d5-44e5-9a6e-056871dd41af
    ESP Path:............/boot/efi
    ESP Partition:......./dev/nvme0n1p1
    ESP Partition #:.....1
    NVRAM entry #:.......-1
    Boot Variable #:.....0000
    Kernel Boot Options:.quiet loglevel=0 systemd.show_status=false splash
    Kernel Image Path:.../boot/vmlinuz
    Initrd Image Path:.../boot/initrd.img
    Force-overwrite:.....False

kernelstub.Installer : INFO     Copying Kernel into ESP
kernelstub.Installer : INFO     Copying initrd.img into ESP
kernelstub.Installer : INFO     Setting up loader.conf configuration
kernelstub.Installer : INFO     Making entry file for Pop!_OS
kernelstub.Installer : INFO     Backing up old kernel
kernelstub.Installer : INFO     Making entry file for Pop!_OS
Errors were encountered while processing:
 system76-r8125-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
I've attached the log file mentioned in the above error messages.
[make.log](https://github.com/pop-os/system76-r8125-dkms/files/4009084/make.log)

**Comment by jackpot51** [comment]
Looks like it needs to be updated for the latest Linux, will do soon

**Comment by lisanhu** [comment]
Thank you!

**Comment by weiklr** [comment]
I have the same issue after upgrading to Pop OS 20.04. Apparently this driver doesn't supports kernel 5.4:

Building for 5.4.0-7626-generic
Building initial module for 5.4.0-7626-generic
ERROR (dkms apport): kernel package linux-headers-5.4.0-7626-generic is not supported
Error! Bad return status for module build on kernel: 5.4.0-7626-generic (x86_64)

**Comment by lisanhu** [comment]
A temporary solution to this is to remove it from the system.
I was trying to upgrade my OS to 20.04 and it stopped me from doing that.
By `lshw`, I realize I'm not using Realtek card, and I've tried `apt info system76-r8125-dkms` one line shows: optional. So I decided to remove the package, and my wifi still works after that.

Then I was able to upgrade my system. Hope this helps.

**Comment by lisanhu** [comment]
A temporary solution to this is to remove it from the system.
I was trying to upgrade my OS to 20.04 and it stopped me from doing that.
By `lshw`, I realize I'm not using Realtek card, and I've tried `apt info system76-r8125-dkms` one line shows: optional. So I decided to remove the package, and my wifi still works after that.

Then I was able to upgrade my system. Hope this helps.

**Comment by jackpot51** [comment]
I don't think this driver is required on the latest Pop!_OS. I will be removing this repository
